# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokendog < Formula
  desc "Token-optimized CLI proxy for AI coding assistants — saves 60-90% of tokens on common dev operations"
  homepage "https://github.com/uttej-badwane/TokenDog"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.19.0/TokenDog_darwin_amd64.tar.gz"
      sha256 "816d62bb882691a2a3b1874fd141aac33a54b98aa313198a6ef2304d5535239a"

      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.19.0/TokenDog_darwin_arm64.tar.gz"
      sha256 "aa109682023d1cb70422d55749179c11c044e4bf381148204eb6ebc5e8e5f414"

      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.19.0/TokenDog_linux_amd64.tar.gz"
      sha256 "5b86cb2f9f72c2355798aa7e795410811cf9138cb2738f0b2ace389398a5eb5e"
      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.19.0/TokenDog_linux_arm64.tar.gz"
      sha256 "399a494d354cf9a5c96d173c6229cab55fae4bb88a2b1b3cbf04ac7393fbb520"
      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      ████████╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗██████╗  ██████╗  ██████╗
      ╚══██╔══╝██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝
         ██║   ██║   ██║█████╔╝ █████╗  ██╔██╗ ██║██║  ██║██║   ██║██║  ███╗
         ██║   ██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║██║  ██║██║   ██║██║   ██║
         ██║   ╚██████╔╝██║  ██╗███████╗██║ ╚████║██████╔╝╚██████╔╝╚██████╔╝
         ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚═════╝

      Token-optimized CLI proxy for AI coding assistants

      Run  td welcome   to see setup status and quick-start guide
      Run  td discover  to find unrewritten commands in your history
      Run  td gain      to see your current token savings
    EOS
  end

  test do
    system "#{bin}/td --version"
    system "#{bin}/tokendog --version"
  end
end
