# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokendog < Formula
  desc "Token-optimized CLI proxy for AI coding assistants — saves 60-90% of tokens on common dev operations"
  homepage "https://github.com/uttej-badwane/TokenDog"
  version "0.18.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.18.1/TokenDog_darwin_amd64.tar.gz"
      sha256 "06e1758bacf69be29989e9eb8b9ebd2da50fbe383ff1bd667d11c17b8a7ed9a3"

      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.18.1/TokenDog_darwin_arm64.tar.gz"
      sha256 "0bd13f099853e6789276f31dd0cc9ed07292051e66e3d9e1fe7e4c444eb5e8e9"

      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.18.1/TokenDog_linux_amd64.tar.gz"
      sha256 "e31af0b654f988429db0c71a392451f8d85c6473fc3ceae56022d34e69f2b302"
      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.18.1/TokenDog_linux_arm64.tar.gz"
      sha256 "41c58d3c19112a8dc9cad35ba9162466a177c12e5281ef3e9ac473f84343bb77"
      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      ████████╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗██████╗  ██████╗  ██████╗
      ╚══██╔══╝██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝
         ██║   ██║   ██║█████╔╝ █████╗  ██╔██╗ ██║██║  ██║██║   ██║██║  ███╗
         ██║   ██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║██║  ██║██║   ██║██║   ██║
         ██║   ╚██████╔╝██║  ██╗███████╗██║ ╚████║██████╔╝╚██████╔╝╚██████╔╝
         ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚═════╝

      Token-optimized CLI proxy for AI coding assistants

      Run  td welcome   to see setup status and quick-start guide
      Run  td discover  to find unrewritten commands in your history
      Run  td gain      to see your current token savings
    EOS
  end

  test do
    system "#{bin}/td --version"
    system "#{bin}/tokendog --version"
  end
end
