# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokendog < Formula
  desc "Token-optimized CLI proxy for AI coding assistants — saves 60-90% of tokens on common dev operations"
  homepage "https://github.com/uttej-badwane/TokenDog"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.5.0/TokenDog_darwin_amd64.tar.gz"
      sha256 "0c0ed6629556cb49001fa35e3ea685eab416f3ca10a7ba915ebe44a4a0534172"

      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.5.0/TokenDog_darwin_arm64.tar.gz"
      sha256 "53d304a0888d160f1cae2ea57a7220b1643864bc5388203fc925a1dc5254c8e2"

      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.5.0/TokenDog_linux_amd64.tar.gz"
      sha256 "f8b2acdbb1720ac19027cad9c30c8dd7b243e1e35da846455f8fe2c82c38dddc"
      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v0.5.0/TokenDog_linux_arm64.tar.gz"
      sha256 "45f4540936475cf78536c03c530cebada884dc06553217d9298709302e8055aa"
      define_method(:install) do
        bin.install "td"
        bin.install_symlink "td" => "tokendog"
        generate_completions_from_executable(bin/"td", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      ████████╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗██████╗  ██████╗  ██████╗
      ╚══██╔══╝██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝
         ██║   ██║   ██║█████╔╝ █████╗  ██╔██╗ ██║██║  ██║██║   ██║██║  ███╗
         ██║   ██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║██║  ██║██║   ██║██║   ██║
         ██║   ╚██████╔╝██║  ██╗███████╗██║ ╚████║██████╔╝╚██████╔╝╚██████╔╝
         ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚═════╝

      Token-optimized CLI proxy for AI coding assistants

      Run  td welcome   to see setup status and quick-start guide
      Run  td discover  to find unrewritten commands in your history
      Run  td gain      to see your current token savings
    EOS
  end

  test do
    system "#{bin}/td --version"
    system "#{bin}/tokendog --version"
  end
end
