# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokendog" do
  binary "td", target: "tokendog"

  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "td"], chdir: ".", writable_paths: ["td"]
    end
  end

  version "0.20.0"

  on_macos do
    on_arm do
      sha256 "a4dabcbe9c5abee746c0b45cf320875e51f247bd93055e10b187fb85bc7eb3ac"
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v#{version}/TokenDog_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "89548b68fb83f6b0cee7ce9b495662143e2a64e8abd657254feadfd402f6f11b"
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v#{version}/TokenDog_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "584f990044b126af92560ab83d38311c0019c0273c7cb7af667f4d08d569f5d9"
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v#{version}/TokenDog_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4d981a39b128b45a3380021273eaf037c07c418aabddca0d41c3a44cb18e4cb"
      url "https://github.com/uttej-badwane/TokenDog/releases/download/v#{version}/TokenDog_linux_amd64.tar.gz"
    end
  end

  name "tokendog"
  desc "Token-optimized CLI proxy for AI coding assistants"
  homepage "https://github.com/uttej-badwane/TokenDog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "td"

  generate_completions_from_executable "td", "completion"

  # No zap stanza required

  caveats <<~EOS
    ████████╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗██████╗  ██████╗  ██████╗
    ╚══██╔══╝██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝
       ██║   ██║   ██║█████╔╝ █████╗  ██╔██╗ ██║██║  ██║██║   ██║██║  ███╗
       ██║   ██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║██║  ██║██║   ██║██║   ██║
       ██║   ╚██████╔╝██║  ██╗███████╗██║ ╚████║██████╔╝╚██████╔╝╚██████╔╝
       ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚═════╝

    Token-optimized CLI proxy for AI coding assistants

    Run  td welcome   to see setup status and quick-start guide
    Run  td discover  to find unrewritten commands in your history
    Run  td gain      to see your current token savings
  EOS
end
